[package]
name = "remytype"
version = "0.0.1"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"

